// <auto-generated />
namespace Library.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingstatus_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingstatus_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202004081125127_adding status_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
